### PR TITLE
Turn it into a side panel

### LINKED ISSUE #67: Fix connection to Etherscan
Etherscan/Gnosisscan uses sub frames and some complicated ASP session handling that breaks loading it in our frame. We should find a solution for this.

### PR DESCRIPTION
**Pull request by jfschwarz**
This PR is a foundational refactoring turning Pilot into a [side panel](https://developer.chrome.com/docs/extensions/reference/api/sidePanel) extension. This allows us to get rid of the iframe wrapping and extra address bar.

closes #67 

**BREAKING CHANGES:**
- All existing connection settings will be lost when upgrading to this new version of the extension

**TODO**

- [x] Make connecting/disconnecting on panel toggle reliable
    - [x] monitoring: Show reload hint for stale tabs (à la Rabby), auto-reload the current tab when opening the panel
    - [x] Reconnect when reopening 
- [x] Sometimes there are still duplicated injections (transactions are recorded double)
- [x] Handle tabs that were open before the extension was installed (no monitoring injected)
- [x] Make simulation start/stop handling reliable
    - [x] Stop simulating by clearing recorded transactions
    - [x] Test with: https://balancer.fi/pools/ethereum/v2/0x3de27efa2f1aa663ae5d458857e731c129069f29000200000000000000000588/add-liquidity
    - [x] Test with https://revoke.cash/ 
    - [x] Visualize the isSimulating state using a special action icon
- [x] Host [connect.pilot.gnosisguild.org](http://connect.pilot.gnosisguild.org/)
- [x] Stop intercepting/tracking RPC traffic on panel close
    - [x] Test
- [x] Test concurrent sessions (with and without simulations) in different windows
- [x] Connect to MetaMask from Panel 
    - [x] Implement EIP1193 provider to use from app, event subscription mgmt & event deduplication (multiple iframes)
    - [x] Can only use iframe on visible tabs for connecting to wallet (rpc requests won’t be handled otherwise)
        - [x] Scenario: open pilot on chrome:// tab, switch to regular tab -> rpc requests are only handled then
        - [x] ~Try to implement a timeout (connect via different tab after timeout)~ (not needed, as only current tab will be used)
    - [x] Immediately inject connect iframe to all open tabs on panel open (otherwise we depend on tab reload before we can interact with the user wallet)
    - [x] Make error handling work (test: reject wallet request)
    - [x] Handle disconnects
    - [x] Test event relaying (account/chain switches)
    - [x] ~Handle the case that no regular tab is open (only chrome://) -> open a new tab with https://connect.pilot/.gnosisguild.org (when the panel is initially opened)~ The extension now waits for a proper tab to become active before establishing connections and communications
- [x] Make inject (former EIP1193 bridge) work again (now the panel app has access to `chrome.` APIs!)
    - [x] Test
    - [x] Integrate in panel
- [x] Make rpc redirect urlFilter use `urlRegex` and combine all rpc urls with ORs (`|`)
    - [x] Test
- [x] Migrate routes to extension storage https://developer.chrome.com/docs/extensions/reference/api/storage
    - [x] Test
- [x] Update developer docs
- [x] ~Panel design updates ([Figma designs](https://www.figma.com/design/dVyATiS3RwYw3S2PrHPyX3/PIlot---Smart-Connection?node-id=12-77006) need to be adjusted to support smaller width)~
- [x] Test connecting to Etherscan

Scenarios that need to be tested (manually):
- [x] Test connecting & recording of transactions from all apps on the [`SAFE_APP_WHITELIST`](https://github.com/gnosisguild/zodiac-pilot/blob/main/extension/src/bridge/SafeAppBridge.ts#L41)
- [x] Test Snapshot order signing

### CODE REVIEW

**Comment by frontendphil** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jfschwarz** [comment]
> I hope I've added enough testing boiler plate to simulate everything needed in a test environment. I just don't know exactly what I would assert.

What I had in mind is _manual_ testing using two browser windows, where each window runs its own simulation/recording session.

**Comment by jfschwarz** [comment]
Collecting some issues noticed during testing here:

- [ ] when Rabby is locked and I close the login popup, it keeps popping up as I navigate in the panel (it should only pop up if I click the connect wallet button)

**Comment by frontendphil** [comment]
>  There's still some race condition: The monitoring alert sometimes appears if I open some app in a fresh tab while the panel is already open

I've just now noticed that opening a tab in the background also inhibits us from connecting immediately. There must be some small condition I've missed so far. Maybe this is all connected... :) I'll have a look into this

**Comment by frontendphil** [comment]
> There's still some race condition: The monitoring alert sometimes appears if I open some app in a fresh tab while the panel is already open

I cannot reproduce this one. However, it also doesn't seem too critical and might be something we could figure out later if this happens more often.

**Comment by frontendphil** [comment]
This morning, I tested WalletConnect, and there seem to be some issues. Admittedly, I've only used MetaMask in the last month. I'll have a look at what's going on.

**Comment by frontendphil** [comment]
I've just tested the whole thing in two different windows. The simulation does not seem to overlap AFAICT. Also, transactions show up only in the window where I interacted with the apps. **However** , I can't have one window use one route and the other window use a different one. @jfschwarz this state is persisted somewhere, I guess and I further guess, that we don't take `windowId` into account there. Is that a show-stopper or just a future improvement?

**Comment by jfschwarz** [comment]
> I've just tested the whole thing in two different windows. The simulation does not seem to overlap AFAICT. Also, transactions show up only in the window where I interacted with the apps. **However** , I can't have one window use one route and the other window use a different one. @jfschwarz this state is persisted somewhere, I guess and I further guess, that we don't take `windowId` into account there. Is that a show-stopper or just a future improvement?

Nice! Right, this makes sense. Let's track it as an issue for future improvement: https://github.com/gnosisguild/zodiac-pilot/issues/232

**Pull request merged**
